DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Traceback (most recent call last):
  File "/home/maror24/ImageAnon/dicom_anon_meta.py", line 22, in <module>
    combined_meta = pd.read_pickle(path_to_combined_meta)
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/pickle.py", line 190, in read_pickle
    with get_handle(
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/labs/collab/Imaging/Imaging-PHI/Emory_Images/Meta/Combined_Meta_2022.pkl'
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Traceback (most recent call last):
  File "/home/maror24/ImageAnon/dicom_anon_meta.py", line 22, in <module>
    combined_meta = pd.read_pickle(path_to_combined_meta)
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/pickle.py", line 190, in read_pickle
    with get_handle(
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/labs/collab/Imaging/Imaging-PHI/Emory_Images/Meta/Combined_Meta_2022.pkl'
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
slurmstepd: error: *** JOB 515788 ON hugenode7 CANCELLED AT 2024-09-06T09:39:28 ***
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Traceback (most recent call last):
  File "/home/maror24/ImageAnon/dicom_anon_meta.py", line 22, in <module>
    combined_meta = pd.read_pickle(path_to_combined_meta)
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/pickle.py", line 190, in read_pickle
    with get_handle(
  File "/labs/kamaleswaranlab/anaconda3/rapids/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/labs/collab/Imaging/Imaging-PHI/Emory_Images/Meta/Combined_Meta_2022.pkl'
